---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
activityData <- read.csv("activity.csv", stringsAsFactors = FALSE)
```

```{r}
totalStepsByDay <- aggregate(steps ~ date, data = activityData, sum, na.rm = TRUE)
```

```{r}
hist(totalStepsByDay$steps, main = "Total Steps Each Day", xlab = "Number of Steps")
```

```{r}
meanSteps <- mean(totalStepsByDay$steps)
medianSteps <- median(totalStepsByDay$steps)

```

```{r}
averageStepsByInterval <- aggregate(steps ~ interval, data = activityData, mean, na.rm = TRUE)
plot(averageStepsByInterval$interval, averageStepsByInterval$steps, type = "l", xlab = "Interval", ylab = "Average Number of Steps", main = "Average Daily Activity Pattern")

```


```{r}
maxStepsInterval <- averageStepsByInterval[which.max(averageStepsByInterval$steps), ]

```

```{r}
missingValues <- sum(is.na(activityData$steps))
```


```{r}
imputedData <- activityData
for(i in 1:nrow(imputedData)) {
  if(is.na(imputedData$steps[i])) {
    imputedData$steps[i] <- averageStepsByInterval$steps[which(averageStepsByInterval$interval == imputedData$interval[i])]
  }
}

```


```{r}
totalStepsByDayImputed <- aggregate(steps ~ date, data = imputedData, sum)
hist(totalStepsByDayImputed$steps, main = "Total Steps Each Day (Imputed)", xlab = "Number of Steps")

```
```{r}
meanStepsImputed <- mean(totalStepsByDayImputed$steps)
medianStepsImputed <- median(totalStepsByDayImputed$steps)

```

```{r}
imputedData$date <- as.Date(imputedData$date)
imputedData$dayType <- ifelse(weekdays(imputedData$date) %in% c("Saturday", "Sunday"), "Weekend", "Weekday")
```


```{r}
library(lattice)
averageStepsByDayType <- aggregate(steps ~ interval + dayType, data = imputedData, mean)
xyplot(steps ~ interval | dayType, data = averageStepsByDayType, layout = c(1, 2), type = "l", xlab = "Interval", ylab = "Number of steps")

```


